#!/usr/bin/env python3
"""
Generates twiddle_table.h: a compile-time-constant twiddle factor table for
DIT_FFT() in Toeplitz_FFT.c, sized for a given ROWLEN (bytes).

C has no constexpr, so cexp() can't be evaluated in a static initializer --
the values have to be computed here, offline, and embedded as literal
float pairs. Declaring the table `static const` (rather than filling it at
runtime into a plain static array) is what actually gets it placed in
.rodata (flash) instead of .bss/.data (RAM); verified against the real
arm-none-eabi-gcc toolchain that a `(re) + (im)*I` literal initializer is
accepted as a constant expression and lands in .rodata with 0 bytes in
.bss/.data.

Invoked by the makefile on every build (regeneration is unconditional --
cheap, and avoids the same stale-cache-on-ROWLEN-change trap documented
elsewhere in this project for object files).

Usage: gen_twiddle_table.py <ROWLEN bytes> > twiddle_table.h
"""
import math
import sys


def fmt_float(x):
    """Format x as a valid C float literal body (no trailing 'f' yet).
    %.9g on an exact value like 1.0 or -0.0 produces "1"/"-0" with no
    decimal point or exponent -- not a valid C floating literal once an
    'f' suffix is appended (e.g. "1f" is a syntax error). Guarantee a '.'
    is present."""
    s = f"{x:.9g}"
    if '.' not in s and 'e' not in s and 'E' not in s:
        s += '.0'
    return s


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <ROWLEN bytes>", file=sys.stderr)
        raise SystemExit(1)

    rowlen = int(sys.argv[1])
    rowbits = rowlen * 8
    if rowbits & (rowbits - 1) != 0:
        print(f"error: ROWLEN*8 ({rowbits}) must be a power of two", file=sys.stderr)
        raise SystemExit(1)

    n = rowbits // 2
    print("// Auto-generated by gen_twiddle_table.py -- DO NOT EDIT.")
    print(f"// Precomputed DIT_FFT twiddle factors for ROWBITS = {rowbits} (ROWLEN = {rowlen} bytes).")
    print("#ifndef TWIDDLE_TABLE_H")
    print("#define TWIDDLE_TABLE_H")
    print()
    print("#include <complex.h>")
    print()
    print(f"static const float complex twiddle_table[{n}] = {{")
    for k in range(n):
        angle = -2.0 * math.pi * k / rowbits
        re = math.cos(angle)
        im = math.sin(angle)
        print(f"    ({fmt_float(re)}f) + ({fmt_float(im)}f)*I,")
    print("};")
    print()
    print("#endif")


if __name__ == "__main__":
    main()
